### ISSUE TITLE
Modelar Banco de Dados em PostgreeSQL

### ISSUE THREAD

**Issue by cleversonahum** [brunoricardojava/OpenBike#11]
Gerar um comando SQL que gere as tabelas necessárias para utilização do projeto e colocar o devido código no arquivo /server/model/database.js para gerar as mesmas utilizando Node JS.

**Comment by brunoricardojava** [comment]
ok, vou tentar fazer isso hoje quando chegar em casa.

**Comment by brunoricardojava** [comment]
Foi de madrugada mas adicionei,  vou fechar a issue até descutirmos sobre e  fizermos o primeiro teste, qualquer coisa voltamos a abrir essa issue...
