### ISSUE TITLE
Researsh the possibilies os use multiple antennas on the RFID

### ISSUE THREAD

**Issue by felipebastosb** [brunoricardojava/OpenBike#3]

**Comment by brunoricardojava** [comment]
Pessoal, se tivermos um micro controlador em cada bicicleta nem vamos precisar de transmissor infra vermelho... Podemos fazer pelo próprio micro controlador e os terminais de alimentação...

**Comment by brunoricardojava** [comment]
Acho que é uma boa ideia...

**Comment by felipebastosb** [comment]
Seria uma proposta interessante a se pensar, já que o OpenBike não é um projeto de estações de bicicletas compartilhadas, apesar de esse ser o passo inicial, (eu acho isso)  e sim um grande laboratório maker voltado para a criação de tecnologias pra bicicletas (sistemas embikados, IoB e etc.). Colocando um microcontrolador em cada bicicleta já possibilitaria que pudêssemos usar ele em projetos/experiencias futuras.

**Comment by brunoricardojava** [comment]
Exatamente, estou pensando seriamente em sugerir o uso do ESP8266, teríamos a identificação da bicicleta pelo  numero MAC do ESP.

**Comment by brunoricardojava** [comment]
Reavaliando a situação, acredito que usarmos apenas os terminais de metal para fazer a comunicação pode não ser muito durável. Podemos fazer uns testes com infra-vermelho em diversas situações e ver como ele se sai. Não é caro....vkkkk
