### ISSUE TITLE
Estações - Tabela

### ISSUE THREAD

**Issue by cleversonahum** [brunoricardojava/OpenBike#6]
Informações referentes a tabela de dados com informações das estações.

**Comment by brunoricardojava** [comment]
# Final:
- ID-Estação;
- Nome temático da estação; 
- Quantidade de encaixes;
- Endereço;
- Localização;
- Todos os Slots {ID(slot):ID(bicicleta)} -> Slot vago = ID(bicicleta) = 0;
- Conectado;
- Ativo(Se esta em operação ou não)...
