### ISSUE TITLE
Criar Schemas das tabelas de bike, estação, usuário e emprétismos

### ISSUE THREAD

**Issue by cleversonahum** [brunoricardojava/OpenBike#9]
Seguir os campos definidos nas issues #5 #6 #7 #10

**Comment by brunoricardojava** [comment]
Não entendi...

**Comment by cleversonahum** [comment]
criar os modelos de dados e tals, dizer quais os campos da tabela, o tipo esperado e tals. Qualquer coisa pesquisa Schema Mongo Node

**Comment by cleversonahum** [comment]
Mudamos e agora estaremos usando o Postgree SQL
